// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiHorarios.Data;

namespace WebApiHorarios.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210205194515_HorariosTable")]
    partial class HorariosTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WebApiHorarios.Model.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DiaDeLaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HorarioApertura")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HorarioCierre")
                        .HasColumnType("time");

                    b.Property<int>("IdNegocio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
